name: VillageCommunity
main: cn.jji8.VillageCommunity.main
version: 1.0
author: jianjianai
api-version: 1.13
softdepend: [Vault]
commands:
  VillageCommunity:
    aliases: [vc]
    description: "VillageCommunity的主命令"
    permission-message: "你没有权限执行此命令"
    usage: /<command> 命令